version: '3'
services:
    app:
        build:
          context: .
          dockerfile: Dockerfile
        ports:
            - ${HTTP_PORT}:80
        volumes:
            - './src:/var/www/html:delegated'
            - './deployment/nginx.conf:/etc/nginx/conf.d/default.conf'
        depends_on:
          - db
        environment:
          - PHP_MEM_LIMIT=${PHP_MEM_LIMIT}
          - UPLOAD_LIMIT=64M
    db:
        image: mysql:5.7
        ports:
            - '3307:3306'
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: ${MYSQL_DATABASE}
          MYSQL_USER: ${MYSQL_USER}
          MYSQL_PASSWORD: ${MYSQL_PASSWORD}